### ISSUE TITLE
Empty Contribution fields in AMS2 Records

### ISSUE THREAD

**Issue by mivillesvik** [WGBH-MLA/ams#565] opened 2021-05-07 17:21 UTC
**Is your feature request related to a problem? Please describe.**
When batch-ingests take place, sometimes there ends up being empty contributor fields (just because of varying levels of involvement in various programs), however the issue then arises that in the resulting AMS2 records the empty contributor fields can't be gotten rid of. 

To see an example check out: cpb-aacip-6b43f5520ea

**Describe the solution you'd like**
It would be nice if we could either tell the AMS2 to ignore empty contribution fields in an ingest or make it easier to delete those empty contribution fields from records!

**Describe alternatives you've considered**
Either of the above solutions would work! 

**Additional context**

**Comment by afred** [comment] 2021-05-11 16:10
## Example
![image](https://user-images.githubusercontent.com/1507490/117848912-c6a92100-b251-11eb-9ff6-d492d44890c6.png)

## And here's the corresponding PBCore
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<pbcoreDescriptionDocument xmlns="http://www.pbcore.org/PBCore/PBCoreNamespace.html" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pbcore.org/PBCore/PBCoreNamespace.html http://www.pbcore.org/xsd/pbcore-2.1.xsd">
<pbcoreAssetType>Program</pbcoreAssetType>
<pbcoreAssetDate dateType="Broadcast">1979</pbcoreAssetDate>
<pbcoreIdentifier source="Sony Ci">d20b542c509a488c9ff044ee73060e10</pbcoreIdentifier>
<pbcoreIdentifier source="http://americanarchiveinventory.org">cpb-aacip-249ace2fbfb</pbcoreIdentifier>
<pbcoreIdentifier source="Local Identifier">Tarheels_in_the_Northwest</pbcoreIdentifier>
<pbcoreTitle titleType="Program">Tarheels in the Northwest</pbcoreTitle>
<pbcoreDescription descriptionType="Program"> Half-hour documentary focusing on the music and cultural traditions of a unique community of North Carolinians, now settled in Darrington, Washington. Released through Southern Educational Communications Association (SECA), PMN and Eastern Educational Network (EEN), 1979. Fully funded by NEA. </pbcoreDescription>
<pbcoreGenre source="AAPB Format Genre" annotation="genre">Documentary</pbcoreGenre>
<pbcoreGenre source="AAPB Topical Genre" annotation="topic">Biography</pbcoreGenre>
<pbcoreGenre source="AAPB Topical Genre" annotation="topic">Race and Ethnicity</pbcoreGenre>
<pbcoreCreator>
<creator>KCTS (Television station : Seattle, Wash.)</creator>
<creatorRole>Producing Organization</creatorRole>
</pbcoreCreator>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor/>
</pbcoreContributor>
<pbcoreContributor>
<contributor>Walkinshaw, Jean</contributor>
<contributorRole>Producer</contributorRole>
</pbcoreContributor>
<pbcoreContributor>
<contributor>Coney, John</contributor>
<contributorRole>Executive Producer</contributorRole>
</pbcoreContributor>
<pbcoreContributor>
<contributor>Lewis, Gladys</contributor>
<contributorRole>Interviewee</contributorRole>
</pbcoreContributor>
<pbcoreContributor>
<contributor>Cope, Bob</contributor>
<contributorRole>Interviewee</contributorRole>
</pbcoreContributor>
<pbcoreContributor>
<contributor>Helton, O.C.</contributor>
<contributorRole>Interviewee</contributorRole>
</pbcoreContributor>
<pbcoreContributor>
<contributor>Morgan, Roy</contributor>
<contributorRole>Interviewee</contributorRole>
</pbcoreContributor>
<pbcoreInstantiation>
<instantiationIdentifier source="Filename">cpb-aacip-a6fa829f221</instantiationIdentifier>
<instantiationIdentifier source="unknown">Tarheels_in_the_Northwest</instantiationIdentifier>
<instantiationPhysical>Hard Drive</instantiationPhysical>
<instantiationLocation>SCCtv Archive</instantiationLocation>
<instantiationMediaType>Moving Image</instantiationMediaType>
<instantiationDuration>00:30:00</instantiationDuration>
<instantiationLanguage>eng</instantiationLanguage>
<instantiationAnnotation annotationType="organization">Seattle Colleges Cable Television</instantiationAnnotation>
</pbcoreInstantiation>
<pbcoreInstantiation>
<instantiationIdentifier source="unknown">cpb-aacip-8bf3cfb175f</instantiationIdentifier>
<instantiationIdentifier source="md5">0ac34a46ba1d013c9ba6dd2b5a5c0b2d</instantiationIdentifier>
<instantiationDate>2020-09-27T01:40:00Z</instantiationDate>
<instantiationDate>2020-09-27T01:53:08Z</instantiationDate>
<instantiationDigital>video/mp4</instantiationDigital>
<instantiationLocation>/Volumes/LOC-005/SCC-TV-proxies/cpb-aacip-249ace2fbfb.mp4</instantiationLocation>
<instantiationMediaType>Moving Image</instantiationMediaType>
<instantiationGenerations>Proxy</instantiationGenerations>
<instantiationFileSize>184705115</instantiationFileSize>
<instantiationTimeStart>01:02:01.355</instantiationTimeStart>
<instantiationDuration>00:28:54.922</instantiationDuration>
<instantiationTracks>2</instantiationTracks>
<instantiationEssenceTrack>
<essenceTrackType>Audio</essenceTrackType>
<essenceTrackIdentifier>0</essenceTrackIdentifier>
<essenceTrackIdentifier>2</essenceTrackIdentifier>
<essenceTrackIdentifier>1</essenceTrackIdentifier>
<essenceTrackEncoding>AAC</essenceTrackEncoding>
<essenceTrackDataRate unitsOfMeasure="kb/s">128256</essenceTrackDataRate>
<essenceTrackDuration>00:28:54.922</essenceTrackDuration>
<essenceTrackAnnotation>81325</essenceTrackAnnotation>
<essenceTrackAnnotation>Lossy</essenceTrackAnnotation>
<essenceTrackAnnotation>83276256</essenceTrackAnnotation>
<essenceTrackAnnotation>No (Explicit)</essenceTrackAnnotation>
<essenceTrackAnnotation>3721355</essenceTrackAnnotation>
<essenceTrackAnnotation>2</essenceTrackAnnotation>
<essenceTrackAnnotation>Container</essenceTrackAnnotation>
<essenceTrackAnnotation>1</essenceTrackAnnotation>
<essenceTrackAnnotation>1024</essenceTrackAnnotation>
<essenceTrackAnnotation>27814273</essenceTrackAnnotation>
<essenceTrackAnnotation>Yes</essenceTrackAnnotation>
<essenceTrackAnnotation>L R</essenceTrackAnnotation>
<essenceTrackAnnotation>0</essenceTrackAnnotation>
<essenceTrackAnnotation>-12</essenceTrackAnnotation>
</instantiationEssenceTrack>
<instantiationEssenceTrack>
<essenceTrackType>Video</essenceTrackType>
<essenceTrackIdentifier>0</essenceTrackIdentifier>
<essenceTrackIdentifier>1</essenceTrackIdentifier>
<essenceTrackEncoding>AVC</essenceTrackEncoding>
<essenceTrackDataRate unitsOfMeasure="kb/s">711000</essenceTrackDataRate>
<essenceTrackFrameRate>29.970</essenceTrackFrameRate>
<essenceTrackBitDepth>8</essenceTrackBitDepth>
<essenceTrackFrameSize>["480"] x ["360"]</essenceTrackFrameSize>
<essenceTrackAspectRatio>1.364</essenceTrackAspectRatio>
<essenceTrackDuration>00:28:54.902</essenceTrackDuration>
<essenceTrackAnnotation>CABAC / 4 Ref Frames</essenceTrackAnnotation>
<essenceTrackAnnotation>360</essenceTrackAnnotation>
<essenceTrackAnnotation>core 148</essenceTrackAnnotation>
<essenceTrackAnnotation>4</essenceTrackAnnotation>
<essenceTrackAnnotation>1.023</essenceTrackAnnotation>
<essenceTrackAnnotation>29970</essenceTrackAnnotation>
<essenceTrackAnnotation>1000</essenceTrackAnnotation>
<essenceTrackAnnotation>368</essenceTrackAnnotation>
<essenceTrackAnnotation>3721355</essenceTrackAnnotation>
<essenceTrackAnnotation>YUV</essenceTrackAnnotation>
<essenceTrackAnnotation>480</essenceTrackAnnotation>
<essenceTrackAnnotation>154987215</essenceTrackAnnotation>
<essenceTrackAnnotation>51995</essenceTrackAnnotation>
<essenceTrackAnnotation>Progressive</essenceTrackAnnotation>
<essenceTrackAnnotation>DropFrame=Yes / 24HourMax=No / IsVisual=No</essenceTrackAnnotation>
<essenceTrackAnnotation>VFR</essenceTrackAnnotation>
<essenceTrackAnnotation>PPF</essenceTrackAnnotation>
<essenceTrackAnnotation>4:2:0</essenceTrackAnnotation>
<essenceTrackAnnotation> cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=3 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=abr / mbtree=1 / bitrate=711 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00 </essenceTrackAnnotation>
<essenceTrackAnnotation>x264</essenceTrackAnnotation>
<essenceTrackAnnotation>Container</essenceTrackAnnotation>
<essenceTrackAnnotation>Yes</essenceTrackAnnotation>
<essenceTrackAnnotation>0.000</essenceTrackAnnotation>
</instantiationEssenceTrack>
<instantiationAnnotation annotationType="organization">American Archive of Public Broadcasting</instantiationAnnotation>
</pbcoreInstantiation>
<pbcoreAnnotation annotationType="Level of User Access" ref="" source="" annotation="" version="">Online Reading Room</pbcoreAnnotation>
<pbcoreAnnotation annotationType="special_collections" ref="" source="" annotation="" version="">jean-walkinshaw</pbcoreAnnotation>
</pbcoreDescriptionDocument>
```

**Comment by afred** [comment] 2021-05-11 18:51
duplicate of #569

**Closed by afred** 2021-05-11 18:51 UTC
